# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: embedding.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'embedding.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x65mbedding.proto\"C\n\x0cQueryRequest\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x11\n\tn_results\x18\x03 \x01(\x05\"J\n\rQueryResponse\x12\x11\n\ttenant_id\x18\x01 \x01(\t\x12\r\n\x05query\x18\x02 \x01(\t\x12\x17\n\x07matches\x18\x03 \x03(\x0b\x32\x06.Match\"\x84\x01\n\x05Match\x12\x10\n\x08\x64ocument\x18\x01 \x01(\t\x12&\n\x08metadata\x18\x02 \x03(\x0b\x32\x14.Match.MetadataEntry\x12\x10\n\x08\x64istance\x18\x03 \x01(\x02\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32:\n\x10\x45mbeddingService\x12&\n\x05Query\x12\r.QueryRequest\x1a\x0e.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'embedding_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MATCH_METADATAENTRY']._loaded_options = None
  _globals['_MATCH_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_QUERYREQUEST']._serialized_start=19
  _globals['_QUERYREQUEST']._serialized_end=86
  _globals['_QUERYRESPONSE']._serialized_start=88
  _globals['_QUERYRESPONSE']._serialized_end=162
  _globals['_MATCH']._serialized_start=165
  _globals['_MATCH']._serialized_end=297
  _globals['_MATCH_METADATAENTRY']._serialized_start=250
  _globals['_MATCH_METADATAENTRY']._serialized_end=297
  _globals['_EMBEDDINGSERVICE']._serialized_start=299
  _globals['_EMBEDDINGSERVICE']._serialized_end=357
# @@protoc_insertion_point(module_scope)
